### ISSUE TITLE
Gitea has published official Terraform Provider in Registry

### ISSUE THREAD

**Issue by sgabenov** [malarinv/terraform-provider-gitea#7]
Hi, i have noticed, that Gitea has published official terraform registry provider - https://registry.terraform.io/providers/go-gitea/gitea/latest
Would be great if you can merge your work in to the official one :)

**Comment by Lerentis** [comment]
Hi @sgabenov ,
it has already been merged (kind of). 
i continued from @malarinv s work over [here](https://github.com/Lerentis/terraform-provider-gitea) and merged some of my changes back directly on gitea.com (see [this merge request](https://gitea.com/gitea/terraform-provider-gitea/pulls/2)) and it looks like they are [shipped](https://github.com/go-gitea/terraform-provider-gitea/commit/7ba385d44a4a8d510e534d8a8d084ddc66301971) to the official provider as well.

i probably need to issue another merge request to the official provider as i added a few more things already since that merge and i was not aware that they published an official provider by now, so thanks for the ping 😃
